//Abort the process of creating new bank account
Cypress.Commands.add('AbortNewBankAccountProcess', () => {
    cy.get('#new-bank-account') //+-Button
        .click()
    cy.contains('Konto hinterlegen')
    cy.get('[class="btn btn-link"]')
        .should('contain', 'Abbrechen')
        .click()
})

//Create new Verrechnungskonto
Cypress.Commands.add('CreateNewVerrechnungskonto', () => {
    cy.get('#new-bank-account')
        .click()
    cy.contains('Konto hinterlegen')
    cy.get('#account_chart_bank_account_attributes_iban')
        .should('not.have.value')
        .type('DE02120300000000202051')
    cy.get('#account_chart_bank_account_attributes_bic')
        .should('not.have.value')
        .type('BYLADEM1001')
    cy.get('#account_chart_account_number')
        .clear()
        .type('18000020')
    cy.get('#account_chart_account_name')
        .should('not.have.value')
        .type('Testbankaccount')
    cy.get('[class="btn btn-primary"]')
        .should('contain', 'Konto speichern')
        .click()
})

//Edit new Verrechnungskonto
Cypress.Commands.add('EditNewVerrechnungskonto', () => {
    cy.contains('tr', 'ZE DKB Testbankaccount 0000202051') 
        .find('a')
        .eq(0)
        .click()
    cy.get('[class="modal-title"]')
        .should('contain', 'Konto bearbeiten')
    cy.get('#account_chart_account_number')
        .should('have.value', '18000020')
        .clear()
        .type('18000010')
    cy.get('#account_chart_account_name')
        .should('have.value', 'ZE DKB Testbankaccount 0000202051')
        .clear()
        .type('Testbankaccount')
    cy.contains('Konto speichern')
        .click()
    cy.contains('Testbankaccount')
    cy.contains('18000010')
})

//Deactivate new Verrechnungskonto
Cypress.Commands.add('DeactivateNewVerrechnungskonto', () => {
    cy.contains('tr', 'Testbankaccount') 
        .find('a')
        .eq(0)
        .click()
    cy.get('[class="btn btn-danger"]')
        .should('contain', 'Konto deaktivieren')
        .click()
})

//Create new Hauptkonto (tbc)

//Edit a Hauptkonto (first version)
//included a recovery of old values
Cypress.Commands.add('EditHauptkonto', () => {
    cy.contains('tr', 'Hauptkonto 1611901004 IBB') 
        .find('a')
        .eq(0)
        .click()
    cy.get('[class="modal-title"]')
        .should('contain', 'Konto bearbeiten')
    cy.get('#account_chart_account_number')
        .should('have.value', '18410010')
        .clear()
        .type('18490010')
    cy.get('#account_chart_account_name')
        .should('have.value', 'Hauptkonto 1611901004 IBB')
        .clear()
        .type('Test Hauptbank')
    cy.contains('Konto speichern')
        .click()
    cy.contains('Test Hauptbank')
    cy.contains('18490010')
    //recovery old values
    cy.contains('tr', 'Test Hauptbank') 
        .find('a')
        .eq(0)
        .click()
    cy.get('#account_chart_account_number')
        .clear()
        .type('18410010')
    cy.get('#account_chart_account_name')
        .clear()
        .type('Hauptkonto 1611901004 IBB')
    cy.contains('Konto speichern')
        .click()
})

